### ISSUE TITLE
Version "latest" cannot be installed

### ISSUE THREAD

**Issue by chikamichi** [smashedtoatoms/asdf-redis#4]
Hi,

Not sure if this is an issue of asdf-redis or asdf "core".
When attempting to `asdf install redis latest`, I get the following error:

> "not in gzip format"

It works when specifying a version tag: `asdf install redis 5.0.7`

**Comment by smashedtoatoms** [comment]
Yea, the way it works right now is literally looks for the version specified.  Since `latest` doesn't exist in their download repo, it downloads a 404 error, and then complains it isn't a gzip.

This might take me a bit to get to, as I just started a new job.  I am actually not sure how I feel about it in general, since the whole point of asdf, in my mind, is to be able to explicitly define specific versions of the things one needs.  The version `latest` is vague, and if that kind of vagueness is acceptable, why not just use brew/apt/yum?  I am sure I am missing a use-case or misunderstanding something, so if that questions comes off as dismissive, that is not how I intended it.  I am just not sure on whether the juice is worth the squeeze.

That all being said, that is a terrible error message.  At a minimum, when I have time, I will try to bubble the actual error up instead of that misleading one.

**Comment by chikamichi** [comment]
Got your point :+1:

"latest" use-case probably is: "I need redis installed on this machine to hack on some sh*t, don't mind the version just gimme the latest please."

**Comment by smashedtoatoms** [comment]
Yea, that is a totally legit reason.  I am just wondering how to make that actually work with the tools.version file.  I need to brain this a bit.

**Comment by smashedtoatoms** [comment]
I am not going to have a chance to fix this any time soon.  If anyone wants to take a stab at a PR for it, I would be grateful.
