### ISSUE TITLE
Starting as a Service

### ISSUE THREAD

**Issue by hergaiety** [smashedtoatoms/asdf-redis#7]
While running on Ubuntu Linux I've noticed that while `redis-server` works I'm unable to start it as a service.

Via `systemctl`
```bash
$ systemctl enable redis-server
Failed to enable unit: Unit file redis-server.service does not exist.
```

Via `update-rc.d`
```bash
update-rc.d redis-server enable
update-rc.d: error: cannot find a LSB script for redis-server
```

I'm unsure what steps I could take to use asdf-redis and launch redis-server as a service.

**Comment by smashedtoatoms** [comment]
There is nothing in asdf that is going to make this easy to run as a service. For one, it would have to be implemented for Mac and all Linux variants. In this case, I wrote this to have ephemeral redis instances that could be versioned for projects. Running it system-wide with something like systemctl is antithetical to that, so it's always going to be kind of a misfit. You can probably create a startup script for it, but even that will likely be harder than normal because it won't run in your shell, so you'll have to fully path the the binary in the .asdf directory. 

I would probably start with the startup script and full path. If someone wants to submit a PR to add that functionality, I'd consider it for sure. It just isn't how I use asdf, so I havent spent any time on it thus far.

**Comment by hergaiety** [comment]
Thanks for the prompt reply! Sounds like a completely reasonable response, I'll close this for now unless someone decides to revive it in the future.

**Comment by scarroll32** [comment]
Would be nice to not have to start it each time.
